<!doctype html>
<html lang="<?=LANG?>">
<head data-template-set="html5-reset" data-rel>
    <meta charset="utf-8">
    <title>Sample App</title>
    <meta name="description" content="Sample Description" />
    <meta name="keywords" content="Sample, Keywords" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- CSS BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <link rel="stylesheet" href="<?=$this->skinPath?>/assets/css/styles.css?v=<?=$this->stylesVersion?>">

    <script src="<?=$this->skinPath?>/assets/js/scripts.js?v=<?=$this->stylesVersion?>"></script>

</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">NISH2 - Sample App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$this->fullBasePath?>"><?=$this->translator->translate('nav_home', 'Homepage')?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$this->fullBasePath?>/contact-us"><?=$this->translator->translate('Contact Form')?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$this->fullBasePath?>/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$this->fullBasePath?>/dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Annotation Tests
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" target="_blank" href="<?=$this->fullBasePath?>/annot-test-php8/1/2">PHP 8 - Sample 1</a></li>
                            <li><a class="dropdown-item" target="_blank" href="<?=$this->fullBasePath?>/annot-test2-php8/1/2">PHP 8 - Sample 2</a></li>
                            <li><hr class="dropdown-divider"></li>

                            <li><a class="dropdown-item" target="_blank" href="<?=$this->fullBasePath?>/annot-test-php7/1/2">PHP 7 - Sample 1</a></li>
                            <li><a class="dropdown-item" target="_blank" href="<?=$this->fullBasePath?>/annot-test2-php7/1/2">PHP 7 - Sample 2</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Memoized Tests
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="<?=$this->fullBasePath?>/memoize-test">First Test</a></li>
                            <li><a class="dropdown-item" href="<?=$this->fullBasePath?>/memoize-test-2">Second Test</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="<?=$this->fullBasePath?>/rest-test" target="_blank">REST Test</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<main>

<div class="container">
    <?php
    if (!empty($this->flashMessages)) {
        foreach ($this->flashMessages as $type => $msgList) {
            foreach ($msgList as $msg) {
                ?>
                <div class="alert alert-<?=($type == 'error' ? 'danger' : $type)?> mb-3"><?=$msg?></div>
                <?php
            }
        }
    }
    ?>

    <?php echo $this->controllerOutput;?>
</div>
</main>

<footer>

</footer>



<!-- BOOTSTRAP JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
</html>